Update mock-deploy.yml

diff --git a/.github/workflows/mock-deploy.yml b/.github/workflows/mock-deploy.yml
--- a/.github/workflows/mock-deploy.yml
+++ b/.github/workflows/mock-deploy.yml
@@ -19,15 +19,81 @@ jobs:
     steps:
       - uses: actions/checkout@v3
 
-      - name: "Waiting for 15s"
-        run: sleep 60
-
-      - name: "Fail half of the time"
+      - name: "Configure aws credentials"
         run: |
-          if [[ $(( RANDOM % 2)) == 0 ]]; then
+          sleep 12
+          if [[ $(( RANDOM % 20)) == 0 ]]; then
             echo "Failing step"
             exit 1
           else
             echo "Step successful"
             exit 0
           fi
+          
+      - name: "Configure aws credentials"
+        run: |
+          sleep 12
+          if [[ $(( RANDOM % 20)) == 0 ]]; then
+            echo "Failing step"
+            exit 1
+          else
+            echo "Step successful"
+            exit 0
+          fi
+          
+      - name: "Run actions/setup-node@v2"
+        run: |
+          sleep 12
+          if [[ $(( RANDOM % 20)) == 0 ]]; then
+            echo "Failing step"
+            exit 1
+          else
+            echo "Step successful"
+            exit 0
+          fi
+          
+      - name: "Run yarn install"
+        run: |
+          sleep 12
+          if [[ $(( RANDOM % 20)) == 0 ]]; then
+            echo "Failing step"
+            exit 1
+          else
+            echo "Step successful"
+            exit 0
+          fi
+          
+      - name: "Synth stack"
+        run: |
+          sleep 12
+          if [[ $(( RANDOM % 20)) == 0 ]]; then
+            echo "Failing step"
+            exit 1
+          else
+            echo "Step successful"
+            exit 0
+          fi
+          
+      - name: "Deploy stack"
+        run: |
+          sleep 12
+          if [[ $(( RANDOM % 20)) == 0 ]]; then
+            echo "Failing step"
+            exit 1
+          else
+            echo "Step successful"
+            exit 0
+          fi
+          
+      - name: "Post configure aws credentials"
+        run: |
+          sleep 12
+          if [[ $(( RANDOM % 20)) == 0 ]]; then
+            echo "Failing step"
+            exit 1
+          else
+            echo "Step successful"
+            exit 0
+          fi
+
+
